name = "ink-pub"
main = "workers/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "ink-pub-db"
database_id = "5dfa35ac-5611-4038-b54f-63870fc52de0"
