name: ink-pub-backend
region: oregon
env: node

build:
  command: npm install --production
  start: npm start

run:
  command: npm start

envVars:
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    generateValue: true
